### ISSUE TITLE
固件是否有开源计划

### ISSUE THREAD

**Issue by HollisMeynell** [RQNG/Micrometer-M07#1]
如题, 或者有类似开放出开发接口, 可以自己实现键盘宏等其他功能的支持计划

**Comment by RQNG** [comment]
不开源，因为这不是我的个人项目。

目前没有开放接口的计划，一方面硬件资源已经用得比较极限了，另一方面我希望这个东西简单直观。

另外，键盘本身支持快捷键，想实现宏可以用现成的快捷键宏软件，比如 Perfect Keyboard Pro，没必要重复造轮子。

**Comment by HollisMeynell** [comment]
了解
