### ISSUE TITLE
目前来看, 设置rt的是磁量而非真正的间距

### ISSUE THREAD

**Issue by HollisMeynell** [RQNG/Micrometer-M07#2]
霍尔传感器的磁通量读数与磁轴按下的距离并非线性关系, 目前来看没有校准或者我使用的磁玉轴是不准确的, 我在rt测试界面里, top与bottom都设置的是总键程的一半, 但是我按4/5左右的时候rt显示才到了一半, 这导致我不得不设置 top:20 bottom:160 才能近似相等

[这里有相关测试](https://e2e.ti.com/support/sensors-group/sensors/f/sensors-forum/915379/drv5056-accurately-measuring-distance-using-hall-effect) 同样幅度的位移, 传感器与磁铁距离越大, 传感器读数的差越小

还有个小问题是在旋钮触发上, 由于触发是key down后立刻发送key up, 导致部分场景下被软件读取精度不够导致无法触发, 或者认为是误触, 希望能加一点点延迟

**Comment by RQNG** [comment]
对于前一个问题，当前的算法是采用磁通量读数的线性变化，但磁铁外磁场在空间的分布并非线性变化，因此调整时并非线性。

让这个键盘能精确地测量实际距离是不现实且不必要的：

* 这种键盘对扫描要求高，引入任何非线性算法都会显著增加扫描压力，这是单片机，不是超算。

* 不同轴体之间，单种轴体不同批次之间都会有差异，只能每种单独校准，更新数据库，工作量极大并且最多就是粗校准。

* 最重要的，之所以说没有必要，是因为手感的非线性，再线性的标定最后也是落实到手感这个非线性的参照物上。

对于后一个问题，这是我遇到过已经解决了的问题，请想办法稳定重现它并告知我方法，才能排错。

**Comment by HollisMeynell** [comment]
你应该也是osu玩家，我就直接以osu举例子了
越到触底就灵敏度越高，也就是更容易松早，到osu里面的表现就是更容易提前释放滑条尾，这是客观存在的，手感非线性这个就看人了~~ppy还认为高刷/低延迟没有意义~~，起码你明确标注了精度1mm但是实际上不是，但是舞厅就没这个问题

复现后面的，你可以设定滚轮旋转为方向键上/下，打开osu stable选歌界面，找谱面难度4个以上的图，转起来游戏里对应不上，经常转了但是游戏内没反应，我这里百分百复现

**Comment by RQNG** [comment]
舞厅只需要校准自己的轴，并且轴体是定制的，当然可以相对精确地校准。

我想做的是一般性的简单明了的方案，如果你很在意线性和精度标注不准确，那市面上敢详细说这件事的厂商很少，因为方案都差不多，计较之下都是问题。

旋钮的问题我收到了会进行测试。
